# 특이값 분해 

In [4]:
import numpy as np
from numpy.linalg import svd

In [18]:
a= np.matrix('1.2,1,0,3.4,11.4,2; 1.6,1,0,-8.3,-11.4,2 ; 1.8,1,0,9.1,23.8,2;2.4,0,1,4,14.8,2;,9.3,0,1,4,28.6,2;,8.1,0,1,4,26.2,2;3.2,0,1,4,16.4,2')
print(a)

[[  1.2   1.    0.    3.4  11.4   2. ]
 [  1.6   1.    0.   -8.3 -11.4   2. ]
 [  1.8   1.    0.    9.1  23.8   2. ]
 [  2.4   0.    1.    4.   14.8   2. ]
 [  9.3   0.    1.    4.   28.6   2. ]
 [  8.1   0.    1.    4.   26.2   2. ]
 [  3.2   0.    1.    4.   16.4   2. ]]


In [13]:
U, Sigma, Vt = svd(a)
print(U.shape, Sigma.shape, Vt.shape)

(7, 7) (6,) (6, 6)


In [19]:
print('V trans matrix:\n',np.round(U, 3))
print('Sigma Value:\n',np.round(Sigma, 3))
print('U  matrix:\n',np.round(Vt, 3))

V trans matrix:
 [[-0.214  0.105 -0.496  0.247  0.797 -0.   ]
 [ 0.219 -0.705 -0.614  0.101 -0.262  0.   ]
 [-0.45   0.444 -0.373  0.413 -0.539  0.   ]
 [-0.279  0.057 -0.253 -0.645 -0.04   0.646]
 [-0.537 -0.421  0.307  0.199  0.041  0.254]
 [-0.492 -0.338  0.21   0.052  0.027 -0.211]
 [-0.309  0.001 -0.188 -0.547 -0.031 -0.689]]
Sigma Value:
 [5.6029e+01 1.0200e+01 3.3820e+00 1.2750e+00 5.1000e-02 0.0000e+00]
U  matrix:
 [[-0.203 -0.008 -0.029 -0.234 -0.948 -0.074]
 [-0.659 -0.015 -0.069  0.73  -0.024 -0.168]
 [ 0.325 -0.438  0.022  0.094 -0.025 -0.832]
 [ 0.132  0.597 -0.739 -0.003  0.012 -0.284]
 [-0.634 -0.082 -0.061 -0.636  0.317 -0.287]
 [ 0.    -0.667 -0.667  0.    -0.     0.333]]


# 원본 행렬로 복원하기 위해서 sigma (문제에서는 D) 를  0을 포함한 대각행렬화

In [26]:
Sigma_mat = np.diag(Sigma)
print(Sigma_mat)
a_ = np.dot(np.dot(U, Sigma_mat), Vt)
print(a)

[[5.60289592e+01 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.02003334e+01 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 3.38227431e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 1.27537495e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  5.07109142e-02 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 3.28479132e-16]]
[[  1.2   1.    0.    3.4  11.4   2. ]
 [  1.6   1.    0.   -8.3 -11.4   2. ]
 [  1.8   1.    0.    9.1  23.8   2. ]
 [  2.4   0.    1.    4.   14.8   2. ]
 [  9.3   0.    1.    4.   28.6   2. ]
 [  8.1   0.    1.    4.   26.2   2. ]
 [  3.2   0.    1.    4.   16.4   2. ]]
